---
fixtures:
  repositories:
    haveged: https://github.com/simp/pupmod-simp-haveged
    stdlib: https://github.com/simp/puppetlabs-stdlib
    simplib: https://github.com/simp/pupmod-simp-simplib
  symlinks:
    simp_pki_service: "#{source_dir}"
