---
fixtures:
  repositories:
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    haveged: https://github.com/simp/pupmod-simp-haveged
    stdlib: https://github.com/simp/puppetlabs-stdlib
    simplib: https://github.com/simp/pupmod-simp-simplib
  symlinks:
    simp_pki_service: "#{source_dir}"
