---
HOSTS:
  ca:
    roles:
    - ca
    - server
    - default
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 4096
    vagrant_cpus: 4
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el7-client:
    roles:
    - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  vagrant_cpus: 1
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
